[package]
name = "ves_lib"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
thiserror = "2"
moka = { version = "0.12", optional = true }
quick_cache = { version = "0.6", optional = true }

[features]
default = []
moka = ["dep:moka"]
quick_cache = ["dep:quick_cache"]

[lints]
workspace = true
